import type {
  AssetHolding,
  Goal,
  InsurancePolicy,
  Liability,
  Property,
} from "@/lib/client-data";

const NOW = "2026-01-15T12:00:00.000Z";

export const TOUR_DEMO_ASSET_HOLDINGS: AssetHolding[] = [
  {
    holding_id: "tour-demo-holding-1",
    user_id: "tour-demo",
    asset_type: "stock",
    valuation_method: "market",
    cost_basis: 12000,
    initial_value_date: "2024-06-01",
    symbol: "AAPL",
    name: "Apple Inc.",
    quantity: 50,
    current_value: 14250,
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    holding_id: "tour-demo-holding-2",
    user_id: "tour-demo",
    asset_type: "etf",
    valuation_method: "market",
    cost_basis: 25000,
    initial_value_date: "2023-01-10",
    symbol: "VTI",
    name: "Vanguard Total Stock Market ETF",
    quantity: 100,
    current_value: 27800,
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    holding_id: "tour-demo-holding-3",
    user_id: "tour-demo",
    asset_type: "cash",
    valuation_method: "manual",
    cost_basis: 18500,
    initial_value_date: "2025-01-01",
    name: "High-yield savings",
    current_value: 19200,
    coupon_rate: 4.2,
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const TOUR_DEMO_PROPERTIES: Property[] = [
  {
    property_id: "tour-demo-property-1",
    user_id: "tour-demo",
    name: "Primary residence",
    property_type: "house",
    country: "United States",
    city: "Austin",
    purchase_date: "2019-08-15",
    purchase_price: 420000,
    market_value: 565000,
    mortgage_balance: 298000,
    mortgage: {
      lender: "Chase",
      balance: 298000,
      interest_rate_pct: 5.85,
      min_payment_monthly: 2140,
      due_day: 1,
    },
    is_primary: true,
    is_active: true,
    insurance: [
      {
        insurance_type: "homeowners",
        provider: "State Farm",
        policy_number: "SF-482910",
        coverage_amount: 580000,
        annual_premium: 1680,
        deductible: 2500,
        expiry_date: "2026-11-01",
      },
    ],
    created_at: NOW,
    updated_at: NOW,
  },
  {
    property_id: "tour-demo-property-2",
    user_id: "tour-demo",
    name: "Rental - East Side",
    property_type: "apartment",
    country: "United States",
    city: "Denver",
    purchase_date: "2021-03-20",
    purchase_price: 310000,
    market_value: 352000,
    mortgage_balance: 198000,
    mortgage: {
      lender: "Wells Fargo",
      balance: 198000,
      interest_rate_pct: 6.1,
      min_payment_monthly: 1485,
      due_day: 15,
    },
    is_primary: false,
    is_active: true,
    insurance: [
      {
        insurance_type: "landlord",
        provider: "Lemonade",
        policy_number: "LM-77342",
        coverage_amount: 340000,
        annual_premium: 920,
        deductible: 1500,
        expiry_date: "2026-08-20",
      },
    ],
    created_at: NOW,
    updated_at: NOW,
  },
];

export const TOUR_DEMO_LIABILITIES: Liability[] = [
  {
    id: "tour-demo-liability-1",
    name: "Chase Sapphire",
    lender: "Chase",
    type: "credit_card",
    balance: 4200,
    interestRatePct: 22.4,
    minPaymentMonthly: 180,
    dueDay: 12,
    updatedAt: NOW,
  },
  {
    id: "tour-demo-liability-2",
    name: "Student loan",
    lender: "Nelnet",
    type: "student_loan",
    balance: 28500,
    interestRatePct: 5.2,
    minPaymentMonthly: 310,
    dueDay: 28,
    updatedAt: NOW,
  },
  {
    id: "tour-demo-liability-3",
    name: "Auto loan",
    lender: "Toyota Financial",
    type: "auto_loan",
    balance: 16400,
    interestRatePct: 4.9,
    minPaymentMonthly: 425,
    dueDay: 5,
    updatedAt: NOW,
  },
];

export const TOUR_DEMO_INSURANCE_POLICIES: InsurancePolicy[] = [
  {
    policy_id: "tour-demo-insurance-1",
    user_id: "tour-demo",
    category: "life",
    provider: "MetLife",
    name: "Term life insurance",
    policy_number: "ML-2022-44190",
    coverage_amount: 1500000,
    premium_monthly: 185,
    deductible: 0,
    start_date: "2022-01-15",
    renewal_date: "2030-06-01",
    auto_renew: false,
    beneficiary: "Spouse",
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    policy_id: "tour-demo-insurance-2",
    user_id: "tour-demo",
    category: "health",
    provider: "Blue Cross Blue Shield",
    name: "Family health plan",
    policy_number: "BC-2025-88320",
    coverage_amount: 500000,
    premium_monthly: 420,
    deductible: 2500,
    start_date: "2025-01-01",
    renewal_date: "2026-12-31",
    auto_renew: true,
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    policy_id: "tour-demo-insurance-3",
    user_id: "tour-demo",
    category: "auto",
    provider: "Geico",
    name: "Auto comprehensive",
    policy_number: "GC-2024-90211",
    coverage_amount: 300000,
    premium_monthly: 145,
    deductible: 500,
    start_date: "2024-03-01",
    renewal_date: "2026-09-01",
    auto_renew: true,
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    policy_id: "tour-demo-insurance-4",
    user_id: "tour-demo",
    category: "disability",
    provider: "Guardian",
    name: "Long-term disability",
    policy_number: "GD-2023-11804",
    coverage_amount: 8000,
    premium_monthly: 95,
    deductible: 0,
    start_date: "2023-06-01",
    renewal_date: "2027-06-01",
    auto_renew: true,
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
];

export const TOUR_DEMO_GOALS: Goal[] = [
  {
    id: "tour-demo-goal-1",
    title: "Emergency fund",
    category: "emergency",
    priority: 1,
    description: "6 months of essential expenses",
    yearsRemaining: 1.5,
    current: 12000,
    target: 30000,
    completed: false,
    monthlyContributionNeeded: 1000,
    probability: 72,
  },
  {
    id: "tour-demo-goal-2",
    title: "Home deposit",
    category: "housing",
    priority: 2,
    description: "Down payment for next property",
    yearsRemaining: 4,
    current: 45000,
    target: 120000,
    completed: false,
    monthlyContributionNeeded: 1560,
    probability: 65,
  },
  {
    id: "tour-demo-goal-3",
    title: "Retirement boost",
    category: "retirement",
    priority: 3,
    yearsRemaining: 18,
    current: 85000,
    target: 500000,
    completed: false,
    monthlyContributionNeeded: 1920,
    probability: 58,
  },
];
